import { useState } from "react";
import Head from "next/head";
import styled from "styled-components";

import Bird from "@/components/Bird";

const Wrapper = styled.div`
  position: relative;
  height: 405px;
  width: 720px;
  margin: 60px auto;
  background: url("/images/background1.jpeg");
  background-size: contain;
  border-radius: 8px;
  box-shadow: rgba(0, 0, 0, 0.45) 1px 1px 6px;
  pointer: cursor;

  @media (max-width: 720px) {
    width: 100vw;
    height: 56.25vw;
    border-radius: 0;
  }
`;

export default function Home() {
  const [x, setX] = useState(50);
  const [y, setY] = useState(50);

  const onLaunch = (e) => {
    const leftOffset = (window.innerWidth - e.target.clientWidth) / 2;
    const topOffset = 60;

    const xval = e.pageX - leftOffset;
    const yval = Math.abs(e.pageY - topOffset - e.target.clientHeight);
    setX(xval);
    setY(yval);

    console.log("x, y", x, y);
  };
  return (
    <>
      <Head>
        <title>Bird Launcher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper onClick={onLaunch} id="background">
        <Bird x={50} y={50}></Bird>
        <div
          style={{
            position: "absolute",
            padding: "16px",
            top: "-60px",
            left: 0,
            fontSize: "32px",
            color: "#fff",
          }}
        >
          {Math.floor(x)},{""} {Math.floor(y)}
        </div>
      </Wrapper>
    </>
  );
}
